name: run-unit-tests
run-name: ${{github.actor}} run unit tests
on:
  push:
    branches: [staging, dev, main]
jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit
