name: Unit Tests
run-name: ${{github.actor}} run unit tests
on:
  push:
    branches: [auto-unit-test]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: Run unit tests
        run: npm run test:unit
        env:
          GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
          GCP_BUCKET: ${{secrets.GCP_BUCKET}}
          DATABASE_URL: $${{secrets.DATABASE_URL}}
      - name: Generate Test Badge
        uses: schneegans/dynamic-badges-action@v1.2.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: 342d1aa6f4715de5044cd252b7c07a61
          filename: personal-page-badge.json
          label: Unit Tests
          message: ${{job.status}}
